- name: appsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup.yml

- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yml

- name: mysql setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup.yml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml

- name: install dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - Cryptography      

- name: import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_IP }}"
    login_user: "{{ user }}"
    login_password: "{{ password }}"
    target: "{{ item }}"

  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql 

- name: start service
  ansible.builtin.service:
    name: "{{ module }}"
    state: restarted
    enabled: yes    
  