[mongodb]
mongodb-dev.krishnadev.space

[catalogue]
catalogue-dev.krishnadev.space

[redis]
redis-dev.krishnadev.space

[user]
user-dev.krishnadev.space

[cart]
cart-dev.krishnadev.space

[mysql]
mysql-dev.krishnadev.space

[shipping]
shipping-dev.krishnadev.space

[rabbitmq]
rabbitmq-dev.krishnadev.space

[payment]
payment-dev.krishnadev.space

[frontend]
frontend-dev.krishnadev.space