- name: install package
  ansible.builtin.dnf:
    name: maven
    state: present

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: install dependencies
  ansible.builtin.command: "mv target/{{ module }}-1.0.jar {{ module }}.jar"
  args:
    chdir: /app    