- name: appsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup.yml

- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml

- name: start cart
  ansible.builtin.service:
    name: cart
    enabled: yes
    state: restarted   